# Site settings
name: Avyay Agarwal
title: Avyay Agarwal | CS Major at UWaterloo | ML Engineering Intern @Twitter
description: Software Engineer aiming to democratize the benefits of technology
url: https://www.avyay.xyz/
baseurl: ''
email: hello@avyay.xyz
cover: https://avyayagarwal.github.io/img/og.png
logo: https://avyayagarwal.github.io/img/emojis/technologist.png
resume: https://www.avyay.xyz/resume.pdf
social:
  - title: email
    url: mailto:hello@avyay.xyz
  # - title: instagram
  #   url: https://instagram.com/avyayagarwal
  # - title: codepen
  #   url: http://codepen.io/avyayagarwal
  - title: github
    url: https://github.com/avyayagarwal
  - title: linkedin
    url: https://www.linkedin.com/in/avyayagarwal
  - title: twitter
    url: https://twitter.com/avyayagarwal

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
