# Site settings
<<<<<<< HEAD
name: Brittany Chiang
title: Brittany Chiang | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bchiang7.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:brittany.chiang@gmail.com
  - title: twitter
    url: https://twitter.com/bchiang7
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/bchiang7
  - title: linkedin
    url: https://www.linkedin.com/in/bchiang7
=======
name: Avyay Agarwal
title: Avyay Agarwal
description: Software Engineer and working to democratize the benefits of technology
url: https://www.avyayagarwal.me/
baseurl: ''
email: avyay99@gmail.com
cover: https://avyayagarwal.github.io/img/og.png
logo: https://avyayagarwal.github.io/img/emojis/technologist.png
resume: https://www.avyayagarwal.me/resume.pdf
social:
  - title: email
    url: mailto:hello@avyayagarwal.me
  - title: twitter
    url: https://twitter.com/avyayagarwal
  - title: instagram
    url: https://instagram.com/avyayagarwal
  # - title: codepen
  #   url: http://codepen.io/avyayagarwal
  - title: github
    url: https://github.com/avyayagarwal
  - title: linkedin
    url: https://www.linkedin.com/in/avyayagarwal
>>>>>>> added changes to starter code from @bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
